leftnav:
- identifier: b78eb105-91e5-a2a5-99b8-4ca60f4122d6
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: external-82dcc95e217140ca9540db2c7e2cd9a2
  name: Quantum Information Science I, Part 1
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.1x+1T2018/about
  weight: 1000
- identifier: external-9c851a5235444ad38b32b7755c9aa344
  name: Quantum Information Science I, Part 2
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.2x+1T2018/about
  weight: 1010
- identifier: external-9cc696b33c594058a91ece17804f2821
  name: Quantum Information Science I, Part 3
  url: https://openlearninglibrary.mit.edu/courses/course-v1:MITx+8.370.3x+1T2018/about
  weight: 1020
